# Generated by Django 2.0.5 on 2018-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('Posted_time', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('markdown_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=50)),
                ('Description', models.TextField(blank=True)),
                ('Date', models.DateField()),
                ('Team_Limit', models.IntegerField()),
                ('Team_Size_Limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=100)),
                ('studentid', models.CharField(max_length=2000)),
                ('studentname', models.CharField(max_length=2000)),
                ('event', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(editable=False, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
    ]
