# Generated by Django 2.0.5 on 2018-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Team_Limit', models.IntegerField()),
                ('Team_Size_Limit', models.IntegerField()),
            ],
        ),
    ]
