# Generated by Django 2.0.5 on 2018-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='studentid',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='studentname',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamid',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='team_name',
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(max_length=50),
        ),
    ]
