# Generated by Django 2.0.5 on 2018-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('Posted_time', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('markdown_text', models.TextField(blank=True)),
            ],
        ),
    ]
