# Generated by Django 2.0.6 on 2018-06-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20180628_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='leader',
        ),
        migrations.AlterField(
            model_name='team_event',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
