# Generated by Django 2.0.5 on 2018-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=100)),
                ('studentid', models.CharField(max_length=2000)),
                ('studentname', models.CharField(max_length=2000)),
                ('event', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(editable=False, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
    ]
