# Generated by Django 2.0.5 on 2018-05-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
