# Generated by Django 2.0.6 on 2018-06-24 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_announcement_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='Posted_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
