# Generated by Django 2.0.6 on 2018-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20180625_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
