# Generated by Django 2.0.6 on 2018-06-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20180627_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_event',
            name='event_id',
        ),
        migrations.AddField(
            model_name='team_event',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Home.event'),
            preserve_default=False,
        ),
    ]
